### ISSUE TITLE
Petri-Foo dish files are locale dependant

### ISSUE THREAD

**Issue by jwm-art-net** [petri-foo/Petri-Foo#19]
"..should really be using the standard XSD types for numeric literals, e.g. xsd:decimal[1], which are not locale dependent.."
see: http://lists.linuxaudio.org/pipermail/linux-audio-dev/2014-February/034665.html

I wouldn't be suprised if there were other cases where the XML could be vastly improved.

**Comment by residuum** [comment]
This can be closed, as #20 is merged.

**Comment by residuum** [comment]
This can be closed, as #20 is merged.
