### ISSUE TITLE
libssl license issue with Debian

### ISSUE THREAD

**Issue by jwm-art-net** [petri-foo/Petri-Foo#22]
We have some licence issue with libssl in debian.
Can you please avoid linking against it directly and use dlopen for it?
Otherwise we could get problem to distribute it :(

http://sourceforge.net/p/petri-foo/mailman/message/32277815/

---

"It is only the SHA1 function from libssl that is used, and it is used
to make a hash of the path to each sample, which is used for
symlinking to samples when 'full-save' is used." - me

"So perhaps there is some other library that provides an SHA1
implementation which does not have any licensing issues as far as
Debian is concerned? If so I'll happily switch to using that library.
Or it may be possible to a different hash function?" - me

My preferred solution would be to choose a different library implementation of the SHA1 hash algorithm.

**Comment by residuum** [comment]
Looks like an easy job, so I'll take it.

**Comment by trebmuh** [comment]
sweat

**Comment by residuum** [comment]
After the merge of #25 this can be closed.
